name       : libinstpatch
homepage   : http://www.swamiproject.org/
version    : 1.1.5
release    : 2
source     :
    - https://github.com/swami/libinstpatch/archive/v1.1.5.tar.gz : 5fd01cd2ba7377e7a72caaf3b565d8fe088b5c8a14e0ea91516f0c87524bcf8a
license    : LGPL-2.1-only
component  : multimedia.library
summary    : libInstPatch stands for lib-Instrument-Patch and is a library for processing
    digital sample based MIDI instrument "patch" files.
description: |
    libInstPatch stands for lib-Instrument-Patch and is a library for processing digital sample based MIDI instrument "patch" files. The types of files libInstPatch supports are used for creating instrument sounds for wavetable synthesis. libInstPatch provides an object framework (based on GObject) to load patch files into, which can then be edited, converted, compressed and saved.
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(sndfile)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
